### ISSUE TITLE
shipjs prepare failed after creating pull request

### ISSUE THREAD

**Issue by KnisterPeter** [algolia/shipjs#327]
**Describe the bug**
Running `shipjs prepare` fails with an error:

```shell
markusw@dell:~/source/tsdi (release/0.20)$ yarn release:prepare
yarn run v1.19.1
$ shipjs prepare
› Checking if `hub` exists.
› Checking the current status.
› Validating mergeStrategy.
› Updating from remote.
$ git pull
Aktueller Branch release/0.20 ist auf dem neuesten Stand.
› Pushing to remote.
$ git push origin release/0.20
Everything up-to-date
› Calculating the next version.
› Confirming the next version.
   The current version: 0.20.3
   The next version: 0.21.0
? Is this next version correct? Yes
› Preparing a staging branch
› Checking out to the staging branch.
$ git checkout -b release-v0.21.0
Zu neuem Branch 'release-v0.21.0' gewechselt
› Updating the version.
› Installing the dependencies.
$ yarn install --silent
› Updating the changelog.
$ /xxx/node_modules/shipjs/node_modules/.bin/conventional-changelog -p angular -i CHANGELOG.md -s
› Committing the changes.
$ git add .
$ git commit --file=/tmp/f7827c15-e4d3-4090-b4ea-7d1247878402
husky > pre-commit (node v12.8.1)
No staged files match any of provided globs.
husky > commit-msg (node v12.8.1)
[release-v0.21.0 fab93e0] chore: release v0.21.0
 2 files changed, 11 insertions(+), 1 deletion(-)
› Creating a pull request.
$ git remote prune origin
entferne veraltete Branches von origin
URL: git@github.com:KnisterPeter/tsdi.git
* [veralteten Branch entfernt] origin/prettier
$ hub pull-request --base release/0.20 --browse --push --file /tmp/e76ee20c-2af8-4110-a3fd-d362fc05fbc8
remote: 
remote: Create a pull request for 'release-v0.21.0' on GitHub by visiting:        
remote:      https://github.com/KnisterPeter/tsdi/pull/new/release-v0.21.0        
remote: 
To github.com:KnisterPeter/tsdi.git
 * [new branch]      HEAD -> release-v0.21.0
Branch 'release-v0.21.0' folgt nun Remote-Branch 'release-v0.21.0' von 'origin'.
[167473:167473:1013/174736.378209:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Wird in einer aktuellen Browsersitzung geöffnet.
     |
     |  chore: release v0.21.0
     |  
     |  ## Release Summary
     |  - Version change: `v0.20.3` → `v0.21.0`
     |  - Merge: `release-v0.21.0` → `release/0.20`
     |  - [Compare the changes between the versions](https://github.com/KnisterPeter/tsdi/compare/v0.20.3...release-v0.21.0)
     |  > :warning: When merging this pull request, you need to **_"Squash and merge"_** and make sure the title starts with `chore: release v0.21.0`.
     |  > After that, a commit `chore: release v0.21.0` will be added and `shipjs trigger` will be able to trigger the release based on the commit.
     |  > Fore more information, please refer to the mergeStrategy section of the [guide](https://github.com/algolia/shipjs/blob/master/GUIDE.md#mergestrategy).
     |  > ![Squash and merge](https://raw.githubusercontent.com/algolia/shipjs/v0.6.0/assets/squash-and-merge.png)
     |  
     |  ---
     |  _This pull request is automatically generated by [Ship.js](https://github.com/algolia/shipjs)_
     |
   
TypeError: Cannot read property 'split' of undefined
    at /home/markusw/source/tsdi/node_modules/shipjs/src/step/prepare/createPullRequest.js:93:27
    at runStep (/home/markusw/source/tsdi/node_modules/shipjs/src/step/runStep.js:17:10)
    at default (/home/markusw/source/tsdi/node_modules/shipjs/src/step/prepare/createPullRequest.js:16:3)
    at prepare (/home/markusw/source/tsdi/node_modules/shipjs/src/flow/prepare.js:65:30)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Proxy.cli (/home/markusw/source/tsdi/node_modules/shipjs/src/cli.js:51:3)
    at async /home/markusw/source/tsdi/node_modules/shipjs/bin/shipjs:6:5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Environment (please complete the following information):**
 - environment: local machine
 - `node -v`: v12.8.1
 - `npm -v` or `yarn -v`: 1.19.1
- Ship.js version: 0.6.0

**Comment by eunjae-lee** [comment]
Hi @KnisterPeter,
Thanks for reporting the error.

Can you still reproduce this situation?
If so, after the error, could you run the following command and tell me what's the output?

```
hub pr list --format="%I %t"
```

This will help me figure out the exact bug.
Thanks for your contribution 😄

**Comment by KnisterPeter** [comment]
Hej @eunjae-lee,

sure. The output is empty. Or in other words, there is no output.

**Comment by KnisterPeter** [comment]
Based on the code in the stacktrace I would guess that the `find` does not match anything and will return `undefined`.

**Comment by eunjae-lee** [comment]
Now that I read your log again, and did you run the command on `release/0.20` branch?

```
markusw@dell:~/source/tsdi (release/0.20)$ yarn release:prepare
```

If you don't specify `mergeStrategy` in `ship.config.js`, by default, it only works on `master` branch`.
And even if you specify it, I don't think you want to run it on `release/0.20` branch.

Anyway, please check it again and let me know what you initially wanted to do.
Thanks!

**Comment by KnisterPeter** [comment]
Hi @eunjae-lee,
you are right, I've executed `prepare` on branch `release/0.20`. As well I've added that branch to my `mergeStrategy` and it created a PR. That all works fine. But afterwards it failed.
I've manually finished the missing parts and did my release.

Now I'm on master again and will try it for my next release. Then I'll report back here.

**Comment by eunjae-lee** [comment]
Thank you. Please know if you have any issues. I'm closing this issue but you can open it later again.

**Comment by eunjae-lee** [comment]
@KnisterPeter It has been reproduced on my side!
The fix will be released in a week.
Thanks :)
