### ISSUE TITLE
failed `release:prepare -f` with npm

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#399]
**Describe the bug**
When I use `release:prepare -f` with npm, there is an error.
However, succeed when I use yarn.

This is the repository that there was an error.
https://github.com/tyankatsu0105/try-shipjs

**To Reproduce**
1. checkout branch develop from master
2. checkout topic branch from develop
3. merge topic branch to develop
4. run `npm run release:prepare -f` on develop branch

**Expected behavior**
Succeed when I use npm.

**Screenshots**
```bash
npm run release:prepare -f
npm WARN using --force I sure hope you know what you are doing.

> try-shipjs@0.0.1 release:prepare /Users/tyankatsu/project/try-shipjs
> shipjs prepare

› Checking if `hub` exists.
› Checking the current status.
› Validating mergeStrategy.
› Updating from remote.
$ git pull origin develop
From github.com:tyankatsu0105/try-shipjs
 * branch            develop    -> FETCH_HEAD
Already up to date.
› Pushing to remote.
$ git push origin develop
Everything up-to-date
› Calculating the next version.
The following commit messages out of convention are ignored:
  Merge pull request #6 from tyankatsu0105/feat/add-changelog
  Merge pull request #5 from tyankatsu0105/docs/add-readme
  build: change shipjs config
  Merge pull request #1 from tyankatsu0105/develop
› Confirming the next version.
The current version: 0.0.1
The next version: 0.0.2
? Is this next version correct? Yes
› Preparing a staging branch
› Checking out to the staging branch.
$ git checkout -b releases/v0.0.2
Switched to a new branch 'releases/v0.0.2'
› Updating the version.
› Installing the dependencies.
$ npm install
npm WARN using --force I sure hope you know what you are doing.
audited 1401 packages in 1.666s
found 0 vulnerabilities

› Updating the changelog.
$ /Users/tyankatsu/project/try-shipjs/node_modules/shipjs/node_modules/.bin/conventional-changelog -p angular -i CHANGELOG.md -s
/bin/sh: /Users/tyankatsu/project/try-shipjs/node_modules/shipjs/node_modules/.bin/conventional-changelog: No such file or directory
Error: {
  "message": "Exit code is 127",
  "command": "/Users/tyankatsu/project/try-shipjs/node_modules/shipjs/node_modules/.bin/conventional-changelog -p angular -i CHANGELOG.md -s",
  "result": ""
}
    at exec (/Users/tyankatsu/project/try-shipjs/node_modules/shipjs-lib/dist/index.esm.js:1700:11)
    at default (/Users/tyankatsu/project/try-shipjs/node_modules/shipjs/src/util/run.js:22:20)
    at /Users/tyankatsu/project/try-shipjs/node_modules/shipjs/src/step/prepare/updateChangelog.js:24:7
    at runStep (/Users/tyankatsu/project/try-shipjs/node_modules/shipjs/src/step/runStep.js:11:10)
    at default (/Users/tyankatsu/project/try-shipjs/node_modules/shipjs/src/step/prepare/updateChangelog.js:6:3)
    at prepare (/Users/tyankatsu/project/try-shipjs/node_modules/shipjs/src/flow/prepare.js:64:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.cli (/Users/tyankatsu/project/try-shipjs/node_modules/shipjs/src/cli.js:57:5)
    at async /Users/tyankatsu/project/try-shipjs/node_modules/shipjs/bin/shipjs:6:5
```

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: 12.13.0
 - `npm -v`: 6.12.0
 - `yarn -v`: 1.19.0
- Ship.js version: 0.8.1

**Additional context**
shipjs is LGTM👍
Thank you for all contributor💚

**Comment by Haroenv** [comment]
IIRC npm doesn't flatten the .bin folder as much as yarn does. I think if we hardcoded a path that could be the cause.
