### ISSUE TITLE
Can I use 'shipjs trigger' if enable npm 2FA?

### ISSUE THREAD

**Issue by Kesin11** [algolia/shipjs#567]
**Describe the bug**
Hi, thanks for creating cool publishing tool.
I try to publish my package using shipjs, but `shipjs trigger` stopped `npm publish --tag latest` phase. I think it could not handle to input one-time password at console.

**To Reproduce**

1. Enable 2FA your npm account
2. Do `shipjs trigger`

**Expected behavior**
`shipjs trigger` will finish correctly.

**Screenshots**
This is log when I do `shipjs trigger`.

```
› Publishing.
$ npm publish --tag latest
npm notice 
npm notice 📦  firestore-simple@5.0.0
npm notice === Tarball Contents === 
npm notice 1.6kB  package.json     
npm notice 3.3kB  CHANGELOG.md     
npm notice 1.1kB  LICENSE          
npm notice 15.2kB README.md        
npm notice 5.7kB  dist/index.d.ts  
npm notice 10.3kB dist/index.js    
npm notice 10.7kB dist/index.js.map
npm notice === Tarball Details === 
npm notice name:          firestore-simple                        
npm notice version:       5.0.0                                   
npm notice package size:  12.0 kB                                 
npm notice unpacked size: 47.8 kB                                 
npm notice shasum:        b9cc6c187ffd37eedad473153740bcd26385ccd2
npm notice integrity:     sha512-smPoFMl2aMs8+[...]EpJVXvbPcuAyA==
npm notice total files:   7                                       
npm notice 
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kesin/.npm/_logs/2019-12-28T07_28_13_849Z-debug.log
Error: {
  "message": "Exit code is 1",
  "command": "npm publish --tag latest",
  "result": ""
}
    at exec (/Users/kesin/github/Firestore-simple/node_modules/shipjs-lib/dist/index.esm.js:1700:11)
    at default (/Users/kesin/github/Firestore-simple/node_modules/shipjs/src/util/run.js:22:20)
    at runStep (/Users/kesin/github/Firestore-simple/node_modules/shipjs/src/step/release/runPublish.js:26:7)
    at runStep (/Users/kesin/github/Firestore-simple/node_modules/shipjs/src/step/runStep.js:11:10)
    at default (/Users/kesin/github/Firestore-simple/node_modules/shipjs/src/step/release/runPublish.js:8:3)
    at release (/Users/kesin/github/Firestore-simple/node_modules/shipjs/src/flow/release.js:51:3)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:303:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firestore-simple@5.0.0 release:trigger: `shipjs trigger`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firestore-simple@5.0.0 release:trigger script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kesin/.npm/_logs/2019-12-28T07_28_13_907Z-debug.log
```

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: v11.0.0
 - `npm -v` or `yarn -v`: 6.9.0
- Ship.js version: 0.12.1

**Additional context**

**Comment by eunjae-lee** [comment]
Hi @Kesin11 
Thank you for reporting the issue. I've never thought about this situation. So it's really helpful that you report this 🙂

![npm auth token](https://docs.npmjs.com/assets/images/getting-started/2fa-auth-pub-select.png)

If you have opted to use 2fa for both authorization and publishing, well I don't know if there's any way to make `shipjs trigger` still work fine.
We should somehow pass over the otp token to shipjs trigger.

Does anyone have an idea? If not, we should guide users not to use 2fa for publishing.

**Comment by eunjae-lee** [comment]
I've added warning message in the guide.
If we get a good idea on this, we will update this again.
