### ISSUE TITLE
Make release:trigger compatible with `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by kazupon** [algolia/shipjs#598]
**Describe the bug**
Unfortunately, `GITHUB_TOKEN` cannot be used to authenticate git commands:
In my github action workflow, it could not release with `release:trigger`. 😞 

The following error occurred in the GitHub action workflow:

```
}
    at exec (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs-lib/dist/index.esm.js:1700:11)
    at default (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/util/run.js:22:20)
    at refs.forEach.ref (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/helper/gitPush.js:23:7)
    at Array.forEach (<anonymous>)
    at gitPush (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/helper/gitPush.js:22:10)
    at runStep (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/step/release/gitPush.js:15:7)
    at runStep (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/step/runStep.js:11:10)
    at default (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/step/release/gitPush.js:7:3)
    at release (/home/runner/work/poeditor-service-provider/poeditor-service-provider/node_modules/shipjs/src/flow/release.js:54:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

See the https://github.com/kazupon/poeditor-service-provider/runs/377176890

**To Reproduce**
1. create the PR with `release:prepare` (https://github.com/kazupon/poeditor-service-provider/pull/36)
2. Label it with `release`
3. Merge it 
4. Triggers release workflow with github action, and run the `release:trigger` (https://github.com/kazupon/poeditor-service-provider/commit/3dace81b5cc45dbf16e8b56758e027104d37c43b/checks?check_suite_id=387723670)

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`:  `10.x`
 - `yarn -v`: `1.19.2` 
- Ship.js version: `0.13.1`

**Additional context**
- Are you using GitHub 2FA Auth?: Yes
- releated info:
  - Make semantic-release compatible with GitHub Actions: https://github.com/semantic-release/semantic-release/issues/1194
  - GItHub Developer docs: https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-22-cloning-the-repository

**Comment by jeetiss** [comment]
Hey @kazupon
Actually this is bug (miss in conception) in github actions that fixed in current version, but as I see you run v1 actions
https://github.com/kazupon/poeditor-service-provider/blob/master/.github/workflows/release.yml#L14-L15

All work nice with latest version of github actions https://github.com/jeetiss/try-shipjs/commit/dc141c3bda63f5ff68a868458f71ed90c9510522/checks?check_suite_id=388868397

If you wanna use v1 actions, you can add custom token `GH_TOKEN` and replace original with them in actions as workaround:
```
      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

**Comment by kazupon** [comment]
@jeetiss 
Thanks!
I'll try to it with `master` version, when I'll plan to release. :)
